# Generated by Django 6.0.6 on 2026-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pan_number', models.CharField(max_length=20)),
                ('loan_type', models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Business Loan', 'Business Loan'), ('Home Loan', 'Home Loan'), ('Education Loan', 'Education Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Gold Loan', 'Gold Loan')], max_length=50)),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Business Owner', 'Business Owner'), ('Freelancer', 'Freelancer')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_tenure_months', models.IntegerField()),
                ('existing_emi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
